version: '3'

services:
  tongate-postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: tongate_dev
      POSTGRES_USER: docker
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: docker

  tongate-server:
    image: tongate-server
    container_name: tongate_server
    depends_on:
      - tongate-postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_URI: "postgres://docker:docker@tongate_postgres:5432/tongate_dev?sslmode=disable"
